### ISSUE TITLE
POST, PUT as ASCII

### ISSUE THREAD

**Issue by maleet** [johnbabb/C--Toggl-Api-Client#7]
POST and PUT are used as ASCII. Should be UTF8 also:

![image](https://cloud.githubusercontent.com/assets/3947730/22057965/c95413c6-dd6f-11e6-93b0-eb27c03baed3.png)

My special characters from title are lost

**Comment by johnbabb** [comment]
I adjusted the source to be Utf8  let me know if that fixes the issue

**Comment by maleet** [comment]
The one from picture works, not Encoding.UTF8.

I use it for this: https://github.com/maleet/jira-toggl-sync
```
System.Net.WebException was unhandled
  HResult=-2146233079
  Message=The request was aborted: The request was canceled.
  Source=System
  StackTrace:
       at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
       at System.Net.ConnectStream.System.Net.ICloseEx.CloseEx(CloseExState closeState)
       at System.Net.ConnectStream.Dispose(Boolean disposing)
       at System.IO.Stream.Close()
       at System.IO.StreamWriter.Dispose(Boolean disposing)
       at System.IO.TextWriter.Dispose()
       at Toggl.Services.ApiService.Get(ApiRequest apiRequest) in E:\GitHub\maleet\jira-toggl-sync\Modules\C--Toggl-Api-Client\Toggl\Services\ApiService.cs:line 172
       at Toggl.Services.ApiService.Put(String url, String data) in E:\GitHub\maleet\jira-toggl-sync\Modules\C--Toggl-Api-Client\Toggl\Services\ApiService.cs:line 117
       at Toggl.Services.TimeEntryService.Edit(TimeEntry obj) in E:\GitHub\maleet\jira-toggl-sync\Modules\C--Toggl-Api-Client\Toggl\Services\TimeEntryService.cs:line 99
       at JiraTogglSync.Services.TogglService.SetWorkLogSynced(WorkLogEntry entry) in E:\GitHub\maleet\jira-toggl-sync\JiraTogglSync.Services\TogglService.cs:line 59
       at JiraTogglSync.Services.WorksheetSyncService.AddWorkLog(WorkLogEntry entry) in E:\GitHub\maleet\jira-toggl-sync\JiraTogglSync.Services\WorksheetSyncService.cs:line 69
       at JiraTogglSync.CommandLine.Program.Main(String[] args) in E:\GitHub\maleet\jira-toggl-sync\JiraTogglSync.CommandLine\Program.cs:line 72
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146232800
       Message=Cannot close stream until all bytes are written.
       Source=System
       StackTrace:
            at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
       InnerException: 

```

**Comment by johnbabb** [comment]
I adjusted the source to use new UTF8Encoding(false)
